/* ことひらいふ「🅿 駐車場」タブ用のデータ（金刀比羅宮参拝者向け）。
   手編集運用（links-data.js / experiences-data.js と同じくコード直書き。Notion連携なし）。

   ── 運用ルール ─────────────────────────────────────────────────────
   ・一時情報として扱う: 料金・台数・営業時間・繁忙期料金は変動が激しい。
     情報を更新したら checked（情報確認日）を必ず新しい日付に差し替える。
   ・電話番号は「行政・事業者の公式公開連絡先（固定電話・法人窓口）」のみ載せる。
     個人オーナー（akippa 等）・私設有人駐車場の個人名／個人携帯番号は載せない。
     運営者不明の私設駐車場は tel:"" とし、参考として役場番号を note に置くにとどめる。
   ・未裏取り値の扱い: 一次情報で確認できず、まとめ記事・地図DB等の二次情報のみに
     基づく値は「600円 ※未裏取り」のように値の中に ※未裏取り を明示するか note に書く。
     レポート（docs/駐車場調査.md）の裏取り区分（◎/○/△・※未裏取り）を消さないこと。
   ・confidence: high=◎ 一次確認済み / medium=○ 一部裏取り / low=△ 未裏取り中心・要現地確認。
   ・出所は docs/駐車場調査.md（2026-07-11 調査）。事実の創作はしない。一次で確認できない
     項目は「不明」または「※未裏取り」と明示する。
   ・group は3分類: 「無料」「有料」（旧・町営＋コインパーキングを統合）「予約」（旧・予約制）。
     絵文字は 無料=🆓 / 有料=🅿 / 予約=📱（index.html の PARKING_EMOJI と対応）。
   ・walk（徒歩目安）は未裏取りが多いため現在非表示（カード・モーダルとも出力しない）。
     データフィールド自体は将来の裏取り用に残す。
   ・show:false のアーカイブ運用: 情報が不正確で表に出せない項目は削除せず show:false にして
     残し、note に非表示理由を書く（例: 旧「臨時」の琴平小・榎井小＝一次404で情報源間相違）。

   ・image（任意）: 琴平町・観光協会等の公式ページのog:imageを assets/places/ にローカル保存したもの
     （出所は imageSource）。Notion同様に画像はリポジトリを正とするlocal-first運用。私設駐車場の
     運営会社ロゴ等は採用しないため、大半の item には image を付けない。

   各itemの形式:
   {id, name, group, operator, address, capacity, price, priceMax, priceBusy,
    hours, payment, reservation, walk, url, tel, confidence, note, map, show,
    image?, imageSource?}
   ・group は groups のいずれか。
   ・priceMax は実際の最大料金額があるときだけ入れる（「該当なし」等の説明文は note へ）。
   ・map は Google マップ検索URL（名称または住所で生成）。 */
window.PARKING_DATA = {
  checked: "2026-07-11",                                   // 情報確認日（更新したらここを変える）
  groups: ["無料", "有料", "予約"],
  items: [

    /* ===== 🆓 無料 ===== */
    {
      id: "pk-kotohira-koen",
      name: "琴平公園駐車場（香川県営）",
      group: "無料",
      operator: "香川県（県営・風致公園）",
      address: "琴平町川西977-2",
      capacity: "13台",
      price: "無料",
      priceMax: "",
      priceBusy: "",
      hours: "不明（一次資料に駐車場の営業時間の記載なし。まとめ記事の『9:00〜17:00・時間外封鎖』は※未裏取り）",
      payment: "無料のため不要",
      reservation: "不明（不可と推測）",
      walk: "不明（参道までの徒歩分数は一次情報になし）",
      url: "https://www.pref.kagawa.lg.jp/documents/13213/10kotohirakouenn.pdf",
      tel: "087-832-3359（香川県交流推進課）／0877-75-6710（琴平町観光商工課）",
      confidence: "high",
      note: "香川県公式PDFで『県営・駐車場無料・13台』を確認。琴平町の町営駐車場一覧には含まれない（町営ではなく県営）。無料のため最大料金・繁忙期料金の概念はなし。トイレなし・標高113m等は※未裏取り。",
      map: "https://www.google.com/maps/search/?api=1&query=琴平公園駐車場 琴平町川西",
      show: true
    },

    /* ===== 🅿 有料（旧「町営」＋旧「コインパーキング」を統合。時間貸し・私設有人を含む） ===== */
    /* -- 町営（琴平町 観光商工課） -- */
    {
      id: "pk-machiei-nishi",
      name: "町営駅前西駐車場",
      group: "有料",
      operator: "琴平町（観光商工課）",
      address: "榎井831-3",
      capacity: "普通53台＋大型5台＝58台",
      price: "普通200円/h・大型400円/h（1時間未満は1時間）",
      priceMax: "普通1,000円／大型2,000円（24h以内・以降繰返し）",
      priceBusy: "特別料金なし（一次確認）",
      hours: "年中無休・24時間営業（臨時休業あり）",
      payment: "現金＋クレカ(Visa/Master/JCB/AMEX/Diners)＋電子マネー(交通系/nanaco/楽天Edy/WAON/iD/QUICPay)＋コード決済(PayPay/d払い/au PAY/楽天ペイ/メルペイ)。電子決済は2026年2月20日開始。ナンバー認証チケットレス方式",
      reservation: "不明（ゲート式）",
      walk: "不明（一次記載なし。『約87m・徒歩約1分』は参考値・※未裏取り）",
      url: "https://www.town.kotohira.kagawa.jp/soshiki/8/11326.html",
      tel: "0877-75-6710（琴平町観光商工課）",
      confidence: "high",
      note: "二輪車不可。所在地は榎井831-3が正。まとめ記事kagawanの旧情報（46台・二輪可・時間限定営業）は不採用。2026-02-20更新の町公式に基づく。",
      map: "https://www.google.com/maps/search/?api=1&query=町営駅前西駐車場 琴平町榎井",
      show: true
    },
    {
      id: "pk-machiei-higashi",
      name: "町営駅前東駐車場",
      group: "有料",
      operator: "琴平町（観光商工課）",
      address: "榎井827-6",
      capacity: "87台（普通のみ・全長5m以下）",
      price: "200円/h（1時間未満は1時間）",
      priceMax: "1,000円（24h以内・以降繰返し）／月極5,000円/月",
      priceBusy: "特別料金なし（一次確認）",
      hours: "土日祝・年末年始(12/29〜1/3)のみ一般利用可。平日は月極契約者専用（一般利用不可）。開閉の具体時刻は公式記載なし",
      payment: "現金＋クレカ＋電子マネー＋コード決済（西と同一・2026年2月20日開始）。ナンバー認証チケットレス方式",
      reservation: "不明。※平日は月極専用、一般利用は土日祝・年末年始のみ",
      walk: "不明（公式記載なし）",
      url: "https://www.town.kotohira.kagawa.jp/soshiki/8/11327.html",
      tel: "0877-75-6710（琴平町観光商工課）",
      confidence: "high",
      note: "重要: 平日は月極専用で一般利用不可、一般利用は土日祝・年末年始のみ。所在地は榎井827-6が正。まとめ記事kagawanの旧情報（32台等）は不採用。月極5,000円/月（令和8年4月1日時点で8台空き）。",
      map: "https://www.google.com/maps/search/?api=1&query=町営駅前東駐車場 琴平町榎井",
      show: true
    },

    /* -- コインパーキング等（時間貸し・私設有人） -- */
    {
      id: "pk-times-konpiramae",
      name: "タイムズ琴平こんぴら前",
      group: "有料",
      operator: "タイムズ24（パーク24）",
      address: "琴平町琴平町631",
      capacity: "119台（うちバス7台）",
      price: "平日60分600円／土日祝60分900円",
      priceMax: "平日600円／土日祝900円（1日）、バス1回1,200円",
      priceBusy: "特別料金の記載なし（通年最大料金）",
      hours: "24時間入出庫可",
      payment: "キャッシュレス専用（現金不可・ページに明記）。クレカ・電子マネー・QR・スマホ精算等。車両制限:全長5m/全幅1.9m/全高2.1m/2.5t",
      reservation: "不明（物件ページ『事前予約可』とタイムズのB『予約不可』で表記割れ・要確認）",
      walk: "不明（一次記載なし。『約4分』は※未裏取り）",
      url: "https://times-info.net/P37-kagawa/C403/park-detail-BUK0035121/",
      tel: "0120-70-8924（タイムズ全国窓口）",
      confidence: "high",
      note: "料金はまとめ記事の約2倍（平日60分600円／土日祝60分900円）が一次情報として正、まとめ記事の『300円/500円』は誤り。台数119台が正（121台は誤り）。現金不可のキャッシュレス専用。予約可否は一次情報内でも割れ、要現地確認。",
      map: "https://www.google.com/maps/search/?api=1&query=タイムズ琴平こんぴら前",
      show: true
    },
    {
      id: "pk-nakanoya-udon",
      name: "中野うどん学校 琴平校 駐車場",
      group: "有料",
      operator: "株式会社中野屋",
      address: "琴平町796",
      capacity: "不明（70台／30台で情報が相違・※未裏取り）",
      price: "有料。うどん作り等の体験者は割引・料金は時期により変動（公式）。『500円/日』は※未裏取り",
      priceMax: "",
      priceBusy: "不明（公式『時期により変動』）",
      hours: "駐車場の供用時間・24時間可否は不明。施設営業はA館8:30〜17:30／B館9:00〜17:00／体験受付9:00〜15:00",
      payment: "不明（まとめ記事の『建物内で店員に前払い』は※未裏取り）",
      reservation: "駐車場単独の予約可否は不明",
      walk: "不明（『金刀比羅宮まで約870m・徒歩約11分』は※未裏取り）",
      url: "https://www.nakanoya.net/access/",
      tel: "0877-75-0001（中野うどん学校）",
      confidence: "medium",
      note: "運営=株式会社中野屋を公式確認。台数・料金は公式に明記がなく※未裏取り（台数70台/30台で相違）。参道近くの別施設『ナカノヤ琴平』とは別物。確定は公式問い合わせ（0877-75-0001）へ。",
      map: "https://www.google.com/maps/search/?api=1&query=中野うどん学校 琴平校",
      show: true
    },
    {
      id: "pk-nice-2-121",
      name: "ナイスパーキング琴平町第2-121",
      group: "有料",
      operator: "株式会社ヨコイ",
      address: "琴平町川西745-1",
      capacity: "13台 ※未裏取り",
      price: "100円/60分 ※未裏取り",
      priceMax: "昼(8-18時)400円／夜(18-8時)300円 ※未裏取り",
      priceBusy: "特別日200円/30分 ※未裏取り（BestPark『200円/30分』とjisya『300円/30分』で相違）",
      hours: "24時間（アグリゲータのみ・一次未確認）",
      payment: "現金のみ（千円札可）・クレカ不可・領収書可 ※未裏取り",
      reservation: "不明（自走式コインパーキング）",
      walk: "不明（『参道まで約6分』は※未裏取り）",
      url: "https://www.yokoi-niceparking.com/",
      tel: "087-885-0114（株式会社ヨコイ）",
      confidence: "medium",
      note: "運営=株式会社ヨコイ・住所は一次確認。台数・料金は第三者DBのみで※未裏取り。特別日料金は情報源間で相違。要現地確認（087-885-0114）。yokoi-niceparking.com に個別ロットページはなし。",
      map: "https://www.google.com/maps/search/?api=1&query=ナイスパーキング琴平町第2",
      show: true
    },
    {
      id: "pk-sanpai",
      name: "琴平参拝駐車場",
      group: "有料",
      operator: "不明（民間・呼び込み型私設駐車場か）",
      address: "琴平町208 ※未裏取り",
      capacity: "約50台 ※未裏取り",
      price: "要確認（700円/400円・500円・500円/300円・300〜1,000円変動など情報源間で不一致・すべて※未裏取り）",
      priceMax: "",
      priceBusy: "変動（1,000円前後 ※未裏取り）",
      hours: "不明（『24時間』はkagawanのみ・※未裏取り。有人誘導のため係員時間帯のみの可能性）",
      payment: "不明",
      reservation: "不明",
      walk: "不明（『表参道階段下まで徒歩5分』は※未裏取り）",
      url: "",
      tel: "",
      confidence: "low",
      note: "△要現地確認。運営者・公式URL・電話番号いずれも一次で特定できず、私設呼び込み駐車場の類型とみられる。料金は情報源間で4通り以上に食い違う。ホテルサイトの同名『琴平参拝駐車場（無料）』と同一か別施設か判別不能。利用前に現地または琴平町役場(0877-75-6700)で確認を。",
      map: "https://www.google.com/maps/search/?api=1&query=琴平参拝駐車場 琴平町",
      show: true
    },
    {
      id: "pk-thepark-2",
      name: "ザ・パーク琴平町第2",
      group: "有料",
      operator: "第一興商『ザ・パーク』（実務:クレスト）",
      address: "琴平町638-2",
      capacity: "29台",
      price: "平日60分300円（夜間100円）／土日祝60分500円",
      priceMax: "平日500円（夜300円）／土日祝1,000円（夜500円）",
      priceBusy: "不明（特別日記載は※未裏取り）",
      hours: "24時間・年中無休",
      payment: "現金（硬貨・紙幣）。プリペイド/クレカ不可はkagawanのみ・※未裏取り",
      reservation: "不明",
      walk: "不明（『石段まで約5分』は※未裏取り。駅基準は徒歩4〜5分）",
      url: "https://www.dkparking.com/",
      tel: "0120-89-8552／0120-162-088（いずれも共通窓口の可能性）",
      confidence: "medium",
      note: "住所638-2・29台・料金は独立第三者DB（Yahoo!地図＝全国駐車場データベース／MapFan）が相互一致で裏付け。至近の別施設『ザ・パーク琴平町』（237／12台／100円30分）と混同注意。運営元サイトはB2Bで一次確認不可。",
      map: "https://www.google.com/maps/search/?api=1&query=ザ・パーク琴平町第2",
      show: true
    },
    {
      id: "pk-ticket-127",
      name: "チケットパーク琴平町-127",
      group: "有料",
      operator: "株式会社ヨコイ（チケットパーク）",
      address: "琴平町（番地245-5は※未裏取り）",
      capacity: "10台",
      price: "平日24h最大200円／土日祝24h最大400円",
      priceMax: "",
      priceBusy: "特別日24h最大1,000円 ※NAVITIME『1,000円』とブログ『400円』で相違",
      hours: "24時間（NAVITIME）",
      payment: "千円札のみ・クレカ不可・領収書可（NAVITIME）",
      reservation: "不明（発券式）",
      walk: "不明（『新町商店街出入口近く／平岡精肉店の目の前』の定性記述のみ・※未裏取り）",
      url: "https://www.yokoi-kk.co.jp/coinparking/",
      tel: "087-885-0114（株式会社ヨコイ）",
      confidence: "medium",
      note: "運営=株式会社ヨコイを公式確認。料金・台数はNAVITIME経由（ヨコイ個別ページ未到達）。特別日料金はNAVITIME『1,000円』とブログ『400円』で食い違い、要現地確認（087-885-0114）。NAVITIME上の名称は『ナイスチケットパーク琴平町127』。",
      map: "https://www.google.com/maps/search/?api=1&query=チケットパーク琴平町",
      show: true
    },
    {
      id: "pk-thepark",
      name: "ザ・パーク琴平町",
      group: "有料",
      operator: "第一興商『ザ・パーク』",
      address: "琴平町237 ※未裏取り",
      capacity: "12台 ※未裏取り",
      price: "全日100円/30分 ※未裏取り",
      priceMax: "平日500円・土日祝1,000円・夜間300円 ※未裏取り",
      priceBusy: "特別日1,000円 ※未裏取り",
      hours: "24時間（地図アグリゲータのみ・※未裏取り）",
      payment: "現金（硬貨・千円札）のみ・クレカ不可（アグリゲータのみ・※未裏取り）",
      reservation: "不明",
      walk: "不明（『石段まで約5分』は※未裏取り）",
      url: "https://www.dkparking.com/",
      tel: "",
      confidence: "low",
      note: "△要現地確認。至近の別施設『ザ・パーク琴平町第2』と台数・住所・単価の取り違えが疑われる。運営元サイトに利用者向け個別ページがなく一次確認不可。電話0120-152-232は他県の別ザ・パークと共通表示のため掲載見送り。",
      map: "https://www.google.com/maps/search/?api=1&query=ザ・パーク琴平町",
      show: true
    },
    {
      id: "pk-kotohira-chushajo",
      name: "琴平駐車場",
      group: "有料",
      operator: "不明（民間有人か）",
      address: "琴平町川東173-5",
      capacity: "60台 ※未裏取り",
      price: "要確認（普通200円/60分等・情報源間で構造が相違・※未裏取り）",
      priceMax: "500円/日 ※未裏取り",
      priceBusy: "",
      hours: "9:00〜19:00（まとめ記事のみ・※未裏取り）",
      payment: "受付での前払い制（有人駐車場・※未裏取り）",
      reservation: "不可とみられる ※未裏取り",
      walk: "不明（『石段まで約8分』は※未裏取り）",
      url: "",
      tel: "",
      confidence: "low",
      note: "△要現地確認。運営者・公式URL・電話は一次で特定できず（民間有人と推測）。住所と名称のみYahoo!地図で独立裏付け。料金は情報源間で構造が異なり※未裏取り。",
      map: "https://www.google.com/maps/search/?api=1&query=琴平駐車場 琴平町川東",
      show: true
    },
    {
      id: "pk-nice-119",
      name: "ナイスパーキング琴平町-119",
      group: "有料",
      operator: "株式会社ヨコイ",
      address: "琴平町川東163-2 ※未裏取り",
      capacity: "5台 ※未裏取り",
      price: "100円/60分 ※未裏取り",
      priceMax: "昼夜各300円 ※未裏取り",
      priceBusy: "特別日 100円/20分 or 200円/30分（相違・※未裏取り）",
      hours: "24時間（二次複数一致・※未裏取り）",
      payment: "現金（千円札）・レシート可・クレカ不可（※未裏取り）",
      reservation: "不明",
      walk: "不明（『参道入口まで約500m・徒歩6分』と『約10分』で相違・※未裏取り）",
      url: "https://www.yokoi-niceparking.com/",
      tel: "087-885-0114（株式会社ヨコイ）",
      confidence: "low",
      note: "△要現地確認。運営=株式会社ヨコイ・電話は公式確認。住所・台数・料金は二次情報のみで※未裏取り。特別日料金は情報源間で相違（2対1でkagawan優勢だが一次未確定）。",
      map: "https://www.google.com/maps/search/?api=1&query=ナイスパーキング琴平町",
      show: true
    },
    {
      id: "pk-station-parking",
      name: "琴平ステーションパーキング",
      group: "有料",
      operator: "不明（独立系）",
      address: "琴平町302",
      capacity: "100台 ※未裏取り",
      price: "日中(6-18時、16時までの入庫)600円均一／夜間(18-6時)100円/30分 ※未裏取り",
      priceMax: "600円（実質日中料金・※未裏取り）",
      priceBusy: "",
      hours: "24時間（カガワン記事のみ・※未裏取り）",
      payment: "不明",
      reservation: "不明",
      walk: "不明（駅基準の値は情報源間でばらつき・※未裏取り）",
      url: "",
      tel: "0877-75-0107（第三者DB一致・運営者公式は未確認）",
      confidence: "low",
      note: "△要現地確認。名称・住所（琴平町302）・固定電話0877-75-0107は複数の独立ディレクトリ（MapFan・スマイティ・ekitan・Yahoo!地図）で一致し比較的信頼度は高いが、運営者公式は未発見。Times/akippa/町営/JR四国系のいずれでもない独立系。台数・料金・24時間はカガワン記事のみ・※未裏取り。確定は0877-75-0107へ照会推奨。",
      map: "https://www.google.com/maps/search/?api=1&query=琴平ステーションパーキング",
      show: true
    },
    {
      id: "pk-thepark-konpira-kaido",
      name: "ザ・パーク金毘羅街道",
      group: "有料",
      operator: "第一興商『ザ・パーク』",
      address: "琴平町269 ※未裏取り",
      capacity: "8台 ※未裏取り",
      price: "平日300円/24h・土日祝400円/24h ※未裏取り",
      priceMax: "不明（24h定額か時間貸か要確認）",
      priceBusy: "特別日700円/24h ※未裏取り",
      hours: "24時間（まとめ記事＋Yahoo!地図・※未裏取り）",
      payment: "不明",
      reservation: "不明",
      walk: "不明（『参道石段まで徒歩約5分』は※未裏取り）",
      url: "https://www.dkparking.com/",
      tel: "",
      confidence: "low",
      note: "△要現地確認。運営ブランド=ザ・パーク（第一興商）は一次確認。住所・台数・料金は二次のみ・※未裏取り。同町内に時間貸＋最大料金制の別ザ・パークが複数あり、『24時間定額制』が実料金体系か要確認。電話0120-152-232は運営者公式で一致確認できず掲載見送り。",
      map: "https://www.google.com/maps/search/?api=1&query=ザ・パーク金毘羅街道 琴平町",
      show: true
    },
    {
      id: "pk-nice-3-123",
      name: "ナイスパーキング琴平町第3-123",
      group: "有料",
      operator: "株式会社ヨコイ",
      address: "不明（榎井835-8／835-6で相違・※未裏取り）",
      capacity: "5台 ※未裏取り",
      price: "100円/60分 ※未裏取り",
      priceMax: "300円系 ※未裏取り",
      priceBusy: "特別日 100円/20分 or 200円/30分（相違・※未裏取り）",
      hours: "24時間と推定（当該ロットの一次記載なし・※未裏取り）",
      payment: "記事に明記なし（近隣ロットは千円札のみ・クレカ不可・領収書可、当該ロットは※未裏取り）",
      reservation: "不明",
      walk: "不明（『石段まで約10分・JR琴平駅近く』は※未裏取り）",
      url: "https://www.yokoi-niceparking.com/",
      tel: "087-885-0114（株式会社ヨコイ）",
      confidence: "low",
      note: "△要現地確認。運営=株式会社ヨコイ・電話は公式確認。住所番地が二次DB間でも相違（BestPark『835-8』vs MapFan『835-6』）し住所自体が不明。台数・料金は二次のみ・※未裏取り。",
      map: "https://www.google.com/maps/search/?api=1&query=ナイスパーキング琴平町第3",
      show: true
    },
    {
      id: "pk-nice-4-171",
      name: "ナイスパーキング琴平町第4-171",
      group: "有料",
      operator: "株式会社ヨコイ",
      address: "琴平町192-8（〒766-0002が正の可能性）※未裏取り",
      capacity: "15台 ※未裏取り",
      price: "100円/60分 ※未裏取り",
      priceMax: "平日昼200/夜300・土日祝昼400/夜300 ※未裏取り",
      priceBusy: "特別日 400円/30分 or 100円/30分（相違・※未裏取り）",
      hours: "24時間（二次のみ・※未裏取り）",
      payment: "QR決済(PayPay・メルペイ・d払い・楽天ペイ、一部au PAY)・クレカ不可・千円札可・領収書可・フラップなし最新機種（二次のみ・※未裏取り）",
      reservation: "不明",
      walk: "不明（『石段まで約7分』は※未裏取り）",
      url: "https://www.yokoi-niceparking.com/",
      tel: "087-885-0114（株式会社ヨコイ）",
      confidence: "low",
      note: "△要現地確認。運営=株式会社ヨコイ・電話は公式確認。郵便番号は766-0004(榎井)ではなく766-0002(川東)が正の可能性が高い。台数・料金は二次のみ・※未裏取り。特別日料金は二次間でも相違。",
      map: "https://www.google.com/maps/search/?api=1&query=ナイスパーキング琴平町第4",
      show: true
    },

    /* ===== 📱 予約（旧「予約制」。akippa 日貸し。個人オーナー運営のため電話は非公開） ===== */
    {
      id: "pk-akippa-komatsucho",
      name: "小松町パーキング（akippa）",
      group: "予約",
      operator: "akippa（個人月極の一部）",
      address: "琴平町785-9（番地は目安）",
      capacity: "不明（3台／19台で相違・※未裏取り）",
      price: "440円〜/日（日貸しのみ・変動あり）",
      priceMax: "",
      priceBusy: "",
      hours: "貸出06:00〜22:00（利用時間制限あり）",
      payment: "akippaアプリ/サイト決済（推測）",
      reservation: "可（akippa日単位予約）",
      walk: "不明（『徒歩約3分』は※未裏取り）",
      url: "https://www.akippa.com/parking/a2206dba7c3e770e0ae531b6abe92400",
      tel: "",
      confidence: "medium",
      note: "対応車種は軽自動車・オートバイのみ（長さ340cm/幅150cm以下）。『全車種対応』は誤り。日貸しのみ440円〜、再入庫可、評価4.7。台数は3台/19台で相違・※未裏取り。正月三が日15時まで進入規制のレビューあり。個人オーナー運営で電話非公開のため予約はakippaページから。",
      map: "https://www.google.com/maps/search/?api=1&query=香川県仲多度郡琴平町785-9",
      show: true
    },
    {
      id: "pk-akippa-kitanocho",
      name: "北野町パーキング（akippa）",
      group: "予約",
      operator: "akippa（個人オーナー）",
      address: "琴平町（番地なし・カーナビは『高灯籠』で検索推奨）",
      capacity: "不明（『9台』は※未裏取り）",
      price: "500円〜/日（日貸しのみ）",
      priceMax: "",
      priceBusy: "繁忙日1,000円（公式ページに2026/8/8・9等が該当日表示）",
      hours: "貸出00:00〜23:59（24時間）",
      payment: "記載なし（akippa予約前提）",
      reservation: "可（akippa日単位予約）",
      walk: "不明（『表参道から外れ混雑を避けやすい』はまとめ記事の主観・※未裏取り）",
      url: "https://www.akippa.com/parking/a891349c81b7639f58581151099df410",
      tel: "",
      confidence: "high",
      note: "日貸しのみ500円〜、繁忙日1,000円。カーナビは『高灯籠』で検索推奨（正しく表示されない旨の公式注意書き）。対応=オートバイ・軽・コンパクト・中型（長さ460cm/幅180cm以下、ワンボックス・大型SUV非対応）。一部縦列。台数『9台』は※未裏取り。個人オーナーで電話非公開。",
      map: "https://www.google.com/maps/search/?api=1&query=高灯籠 琴平町",
      show: true
    },
    {
      id: "pk-akippa-ekikita",
      name: "琴平駅北駐車場（akippa）",
      group: "予約",
      operator: "akippa（個人区画）",
      address: "琴平町362-12",
      capacity: "不明（7台／16台で相違・※未裏取り）",
      price: "200円〜/日（日により変動）",
      priceMax: "300円/日（繁忙期最高）",
      priceBusy: "繁忙期最高300円/日",
      hours: "00:00〜23:59（24時間）",
      payment: "不明（akippaは原則アプリ事前決済）",
      reservation: "可（akippa日貸し・時間貸し非対応）",
      walk: "不明（『約12分』は※未裏取り）",
      url: "https://www.akippa.com/parking/7d5d60075729e0e08d72a34e96dd3278",
      tel: "",
      confidence: "medium",
      note: "日貸しのみ・時間貸し非対応・再入庫可・区画変更可。進入路が狭く急坂（公式注意書き）。車両制限 長さ500cm/幅260cm以下。台数は7台/16台で相違・※未裏取り。個人区画とみられ電話非公開。",
      map: "https://www.google.com/maps/search/?api=1&query=香川県仲多度郡琴平町362-12",
      show: true
    },
    {
      id: "pk-akippa-sato",
      name: "佐藤駐車場（akippa）",
      group: "予約",
      operator: "akippa（個人オーナー）",
      address: "榎井67-2",
      capacity: "不明（『23台』は※未裏取り）",
      price: "150円〜/日（曜日変動）。土日など指定日200円",
      priceMax: "",
      priceBusy: "指定日200円",
      hours: "貸出00:00〜23:59（24時間）",
      payment: "不明（akippaは原則アプリ内事前決済）",
      reservation: "可（akippa日貸し・時間貸し非対応）",
      walk: "不明（『石段まで約19分』は※未裏取り）",
      url: "https://www.akippa.com/parking/277e7c890c58077ecc69f72f5c2b1535",
      tel: "",
      confidence: "medium",
      note: "時間貸し非対応（日貸しのみ）で最大料金の概念なし。評価4.9。車両制限 長さ500cm/幅260cm以下・オートバイ〜大型SUV対応。台数『23台』は※未裏取り。個人管理で電話非公開。",
      map: "https://www.google.com/maps/search/?api=1&query=香川県仲多度郡琴平町榎井67-2",
      show: true
    },

    /* ===== 🚸 臨時（アーカイブ・非表示） =====
       旧グループ「臨時」の年末年始限定駐車場。情報が不正確（町公式ページが一次404・
       情報源間で台数/料金が相違）のため show:false で非表示にしてアーカイブ。削除はしない。
       年末年始前に一次情報で裏取りできたら show:true に戻して再掲する。 */
    {
      id: "pk-rinji-kotohira-sho",
      name: "琴平小学校グラウンド臨時駐車場（年末年始限定）",
      group: "臨時",
      operator: "不明（琴平町か）",
      address: "琴平町（145-1は※未裏取り）",
      capacity: "約200台 or 約100台（相違・※未裏取り）",
      price: "1回1,000円 or 500円（相違・※未裏取り）",
      priceMax: "",
      priceBusy: "",
      hours: "kagawan『12/31 22:00〜17:00(オールナイト)、1/1〜3 9:00〜17:00』・※未裏取り（交通規制図の道路規制時間とは別物に注意）",
      payment: "不明（学校グラウンド開放型のため先着・現地精算と推測）",
      reservation: "不明（先着と推測）",
      walk: "不明（『徒歩約10分』は※未裏取り）",
      url: "",
      tel: "",
      confidence: "low",
      note: "【非表示（アーカイブ）】情報が不正確（町公式ページが一次404・情報源間で台数/料金が相違）のため非表示。年末年始前に裏取りできたら再掲する。／△要現地確認。開設期間=2025/12/31〜2026/1/3（令和8年新春）。町公式ページ・交通規制図で臨時P指定の事実は確認済みだが、町公式ページ(soshiki/8/5637.html)は現在404で、台数・料金・営業時間は一次確認できず情報源間で相違・※未裏取り。均一料金制で最大料金の概念なし。毎年の確定情報は琴平町役場 観光商工課(0877-75-6710)へ照会を。",
      map: "https://www.google.com/maps/search/?api=1&query=琴平小学校 琴平町",
      show: false
    },
    {
      id: "pk-rinji-enai-sho",
      name: "榎井小学校臨時駐車場（年末年始限定）",
      group: "臨時",
      operator: "琴平町（推定）",
      address: "榎井（58-3は※未裏取り）",
      capacity: "約100台 or 約200台（相違・※未裏取り）",
      price: "1回1,000円 or 700円（相違・※未裏取り）",
      priceMax: "",
      priceBusy: "",
      hours: "kagawan『12/31 22:00〜17:00、1/1〜3 9:00〜17:00』・※未裏取り",
      payment: "不明",
      reservation: "不明",
      walk: "不明（『表参道まで徒歩約20分』は※未裏取り）",
      url: "",
      tel: "",
      confidence: "low",
      note: "【非表示（アーカイブ）】情報が不正確（町公式ページが一次404・情報源間で台数/料金が相違）のため非表示。年末年始前に裏取りできたら再掲する。／△要現地確認。開設期間=2025/12/31〜2026/1/3。前年までの神事場臨時駐車場を閉鎖し榎井小学校に変更した経緯を確認。町公式ページは現在404で台数・料金は一次確認できず・※未裏取り。所在地番地も※未裏取り。均一料金制で最大料金の概念なし。毎年の確定情報は琴平町役場 観光商工課(0877-75-6710)へ照会を。",
      map: "https://www.google.com/maps/search/?api=1&query=榎井小学校 琴平町",
      show: false
    }
  ]
};
